# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'FWPopupViewOC' do
  
  use_frameworks!
  
  # 布局：https://github.com/SnapKit/Masonry
  pod 'Masonry'
  
end
